/**
 * oli-runtime.config.ts — Dentalemon runtime-loop config (generated by
 * /oli-check --runtime --live, then committed). The runner reads this + the
 * CODE_* maps at run time.
 */
export interface DataSurfaceBinding {
  route: string;
  openerTestid: string;
  surfaceTestid: string;
  label: string;
  component?: string;
}

export interface OliRuntimeConfig {
  baseURL: string;
  mapsDir: string;
  resultsOut: string;
  contractVersion: number;
  skeletonCeilingMs: number;
  skeletonSelectors: string;
  loadingTextSource: string;
  ignoreUrlSource: string;
  testids: Record<string, string>;
  dataSurfaces: DataSurfaceBinding[];
  paramFixtures: Record<string, string>;
  denyRoutes: string[];
  maxTargets: number;
  navLinkCheck: boolean;
}

export const config: OliRuntimeConfig = {
  baseURL: "http://localhost:3003",
  // cwd when running `playwright test` is apps/dentalemon → repo root is two up.
  mapsDir: "../../docs/audits/codebase-map",
  resultsOut: "../../docs/audits/runtime/runtime-exec-results.json",
  contractVersion: 5,

  skeletonCeilingMs: 5000,
  skeletonSelectors:
    '[aria-busy="true"], .skeleton, [data-loading="true"], [data-testid$="-skeleton"], [data-testid$="-loader"]',
  loadingTextSource: "\\b(loading|saving|fetching|please wait)\\b",
  ignoreUrlSource:
    "\\.(png|jpe?g|svg|gif|webp|ico|woff2?|ttf|css|map)(\\?|$)|/@vite/|/__vite|/hmr|/node_modules/|analytics|posthog|sentry|onesignal|intercom|hotjar|fullstory|segment",

  testids: {},
  dataSurfaces: [
    {
      route: "/_workspace/$patientId",
      openerTestid: "recalls-tab-btn",
      surfaceTestid: "recalls-sheet",
      label: "Recalls",
      component: "RecallsSheet",
    },
    {
      route: "/_workspace/$patientId",
      openerTestid: "treatment-plans-tab-btn",
      surfaceTestid: "treatment-plans-sheet",
      label: "Plans",
      component: "TreatmentPlansSheet",
    },
  ],
  paramFixtures: {},
  // auth/PIN routes need flows we don't drive in a smoke; the patient page is the focus.
  // imaging-test / imaging-comparison-test are DEV HARNESS routes that mount the
  // imaging components with hard-coded fake image IDs (test-image-id), so their
  // ceph/measurement fetches 500 by design — not product routes; exclude them.
  denyRoutes: [
    "/auth/$authView",
    "/auth/pin-entry/$memberId",
    "/imaging-test",
    "/imaging-comparison-test",
  ],
  maxTargets: 500,
  navLinkCheck: true,
};
