/**
 * Seed: Invoices, payments, and payment plans
 */
import type { DatabaseInstance } from './types';
import { dentalInvoices, dentalInvoiceLineItems } from '@/handlers/dental-billing/repos/dental-invoice.schema';
import { dentalPayments } from '@/handlers/dental-billing/repos/dental-payment.schema';
import { dentalPaymentPlans, dentalPaymentPlanInstallments } from '@/handlers/dental-billing/repos/dental-payment-plan.schema';
import {
  BRANCH_ID, DR_REYES_MEMBERSHIP_ID, ANA_SANTOS_MEMBERSHIP_ID,
  PATIENT_JUAN_ID, PATIENT_ROSA_ID, PATIENT_CARLOS_ID, PATIENT_LIZA_ID, PATIENT_BEN_ID,
  VISIT_01, VISIT_02, VISIT_03, VISIT_04, VISIT_05, VISIT_06, VISIT_07, VISIT_09,
  TREATMENT_01, TREATMENT_02, TREATMENT_03, TREATMENT_04, TREATMENT_05,
  TREATMENT_06, TREATMENT_07, TREATMENT_09,
  INVOICE_01, INVOICE_02, INVOICE_03, INVOICE_04, INVOICE_05, INVOICE_06, INVOICE_07, INVOICE_08,
  PAYMENT_01, PAYMENT_02, PAYMENT_03, PAYMENT_04, PAYMENT_05, PAYMENT_06, PAYMENT_07,
  PLAN_01,
  LINE_ITEM_01, LINE_ITEM_02, LINE_ITEM_03, LINE_ITEM_04,
  LINE_ITEM_05, LINE_ITEM_06, LINE_ITEM_07, LINE_ITEM_08,
  INSTALLMENT_01, INSTALLMENT_02, INSTALLMENT_03, INSTALLMENT_04,
} from './ids';

export async function seedBilling(db: DatabaseInstance): Promise<void> {
  console.log('   Seeding billing...');

  // ── 1. Invoices ───────────────────────────────────────────────────
  await db.insert(dentalInvoices).values([
    // INV-2026-0001: Juan V1, paid
    {
      id: INVOICE_01,
      visitId: VISIT_01,
      patientId: PATIENT_JUAN_ID,
      branchId: BRANCH_ID,
      dentistMemberId: DR_REYES_MEMBERSHIP_ID,
      invoiceNumber: 'INV-2026-0001',
      status: 'paid',
      subtotalCents: 150000,
      discountCents: 0,
      taxCents: 0,
      totalCents: 150000,
      paidCents: 150000,
      balanceCents: 0,
      issuedAt: new Date('2026-03-10T02:00:00Z'),
      paidAt: new Date('2026-03-10T02:00:00Z'),
      createdBy: DR_REYES_MEMBERSHIP_ID,
      updatedBy: DR_REYES_MEMBERSHIP_ID,
    },
    // INV-2026-0002: Juan V2, paid
    {
      id: INVOICE_02,
      visitId: VISIT_02,
      patientId: PATIENT_JUAN_ID,
      branchId: BRANCH_ID,
      dentistMemberId: DR_REYES_MEMBERSHIP_ID,
      invoiceNumber: 'INV-2026-0002',
      status: 'paid',
      subtotalCents: 250000,
      discountCents: 0,
      taxCents: 0,
      totalCents: 250000,
      paidCents: 250000,
      balanceCents: 0,
      issuedAt: new Date('2026-04-21T03:30:00Z'),
      paidAt: new Date('2026-04-21T03:30:00Z'),
      createdBy: DR_REYES_MEMBERSHIP_ID,
      updatedBy: DR_REYES_MEMBERSHIP_ID,
    },
    // INV-2026-0003: Rosa V1, paid
    {
      id: INVOICE_03,
      visitId: VISIT_03,
      patientId: PATIENT_ROSA_ID,
      branchId: BRANCH_ID,
      dentistMemberId: DR_REYES_MEMBERSHIP_ID,
      invoiceNumber: 'INV-2026-0003',
      status: 'paid',
      subtotalCents: 80000,
      discountCents: 0,
      taxCents: 0,
      totalCents: 80000,
      paidCents: 80000,
      balanceCents: 0,
      issuedAt: new Date('2026-02-28T07:00:00Z'),
      paidAt: new Date('2026-02-28T07:00:00Z'),
      createdBy: DR_REYES_MEMBERSHIP_ID,
      updatedBy: DR_REYES_MEMBERSHIP_ID,
    },
    // INV-2026-0004: Rosa V2, partial (root canal PHP15k, paid PHP5k)
    {
      id: INVOICE_04,
      visitId: VISIT_04,
      patientId: PATIENT_ROSA_ID,
      branchId: BRANCH_ID,
      dentistMemberId: DR_REYES_MEMBERSHIP_ID,
      invoiceNumber: 'INV-2026-0004',
      status: 'partial',
      subtotalCents: 1500000,
      discountCents: 0,
      taxCents: 0,
      totalCents: 1500000,
      paidCents: 500000,
      balanceCents: 1000000,
      issuedAt: new Date('2026-03-31T01:00:00Z'),
      createdBy: DR_REYES_MEMBERSHIP_ID,
      updatedBy: DR_REYES_MEMBERSHIP_ID,
    },
    // INV-2026-0005: Carlos V1, paid
    {
      id: INVOICE_05,
      visitId: VISIT_05,
      patientId: PATIENT_CARLOS_ID,
      branchId: BRANCH_ID,
      dentistMemberId: DR_REYES_MEMBERSHIP_ID,
      invoiceNumber: 'INV-2026-0005',
      status: 'paid',
      subtotalCents: 150000,
      discountCents: 0,
      taxCents: 0,
      totalCents: 150000,
      paidCents: 150000,
      balanceCents: 0,
      issuedAt: new Date('2026-03-05T04:00:00Z'),
      paidAt: new Date('2026-03-05T04:00:00Z'),
      createdBy: DR_REYES_MEMBERSHIP_ID,
      updatedBy: DR_REYES_MEMBERSHIP_ID,
    },
    // INV-2026-0006: Carlos V2, issued (crown PHP20k — payment plan)
    {
      id: INVOICE_06,
      visitId: VISIT_06,
      patientId: PATIENT_CARLOS_ID,
      branchId: BRANCH_ID,
      dentistMemberId: DR_REYES_MEMBERSHIP_ID,
      invoiceNumber: 'INV-2026-0006',
      status: 'issued',
      subtotalCents: 2000000,
      discountCents: 0,
      taxCents: 0,
      totalCents: 2000000,
      paidCents: 0,
      balanceCents: 2000000,
      issuedAt: new Date('2026-04-07T02:30:00Z'),
      dueDate: new Date('2026-08-31T16:00:00Z'),
      createdBy: DR_REYES_MEMBERSHIP_ID,
      updatedBy: DR_REYES_MEMBERSHIP_ID,
    },
    // INV-2026-0007: Liza V1, paid
    {
      id: INVOICE_07,
      visitId: VISIT_07,
      patientId: PATIENT_LIZA_ID,
      branchId: BRANCH_ID,
      dentistMemberId: DR_REYES_MEMBERSHIP_ID,
      invoiceNumber: 'INV-2026-0007',
      status: 'paid',
      subtotalCents: 150000,
      discountCents: 0,
      taxCents: 0,
      totalCents: 150000,
      paidCents: 150000,
      balanceCents: 0,
      issuedAt: new Date('2026-04-14T07:45:00Z'),
      paidAt: new Date('2026-04-14T07:45:00Z'),
      createdBy: DR_REYES_MEMBERSHIP_ID,
      updatedBy: DR_REYES_MEMBERSHIP_ID,
    },
    // INV-2026-0008: Ben V2, paid (extraction PHP5k)
    {
      id: INVOICE_08,
      visitId: VISIT_09,
      patientId: PATIENT_BEN_ID,
      branchId: BRANCH_ID,
      dentistMemberId: DR_REYES_MEMBERSHIP_ID,
      invoiceNumber: 'INV-2026-0008',
      status: 'paid',
      subtotalCents: 500000,
      discountCents: 0,
      taxCents: 0,
      totalCents: 500000,
      paidCents: 500000,
      balanceCents: 0,
      issuedAt: new Date('2026-04-21T07:00:00Z'),
      paidAt: new Date('2026-04-21T07:00:00Z'),
      createdBy: DR_REYES_MEMBERSHIP_ID,
      updatedBy: DR_REYES_MEMBERSHIP_ID,
    },
  ]).onConflictDoNothing();

  // ── 2. Invoice Line Items ─────────────────────────────────────────
  await db.insert(dentalInvoiceLineItems).values([
    { id: LINE_ITEM_01, invoiceId: INVOICE_01, treatmentId: TREATMENT_01, cdtCode: 'D1110', description: 'Oral Prophylaxis', unitPriceCents: 150000, quantity: 1, amountCents: 150000, isDone: true, createdBy: DR_REYES_MEMBERSHIP_ID, updatedBy: DR_REYES_MEMBERSHIP_ID },
    { id: LINE_ITEM_02, invoiceId: INVOICE_02, treatmentId: TREATMENT_02, cdtCode: 'D2391', description: 'Composite filling — 1 surface, #30', toothNumber: 30, unitPriceCents: 250000, quantity: 1, amountCents: 250000, isDone: true, createdBy: DR_REYES_MEMBERSHIP_ID, updatedBy: DR_REYES_MEMBERSHIP_ID },
    { id: LINE_ITEM_03, invoiceId: INVOICE_03, treatmentId: TREATMENT_03, cdtCode: 'D0330', description: 'Panoramic radiograph', unitPriceCents: 80000, quantity: 1, amountCents: 80000, isDone: true, createdBy: DR_REYES_MEMBERSHIP_ID, updatedBy: DR_REYES_MEMBERSHIP_ID },
    { id: LINE_ITEM_04, invoiceId: INVOICE_04, treatmentId: TREATMENT_04, cdtCode: 'D3330', description: 'Root canal — molar, #14', toothNumber: 14, unitPriceCents: 1500000, quantity: 1, amountCents: 1500000, isDone: false, createdBy: DR_REYES_MEMBERSHIP_ID, updatedBy: DR_REYES_MEMBERSHIP_ID },
    { id: LINE_ITEM_05, invoiceId: INVOICE_05, treatmentId: TREATMENT_05, cdtCode: 'D1110', description: 'Oral Prophylaxis', unitPriceCents: 150000, quantity: 1, amountCents: 150000, isDone: true, createdBy: DR_REYES_MEMBERSHIP_ID, updatedBy: DR_REYES_MEMBERSHIP_ID },
    { id: LINE_ITEM_06, invoiceId: INVOICE_06, treatmentId: TREATMENT_06, cdtCode: 'D2750', description: 'PFM Crown, #19', toothNumber: 19, unitPriceCents: 2000000, quantity: 1, amountCents: 2000000, isDone: true, createdBy: DR_REYES_MEMBERSHIP_ID, updatedBy: DR_REYES_MEMBERSHIP_ID },
    { id: LINE_ITEM_07, invoiceId: INVOICE_07, treatmentId: TREATMENT_07, cdtCode: 'D1110', description: 'Oral Prophylaxis', unitPriceCents: 150000, quantity: 1, amountCents: 150000, isDone: true, createdBy: DR_REYES_MEMBERSHIP_ID, updatedBy: DR_REYES_MEMBERSHIP_ID },
    { id: LINE_ITEM_08, invoiceId: INVOICE_08, treatmentId: TREATMENT_09, cdtCode: 'D7210', description: 'Surgical extraction, #18', toothNumber: 18, unitPriceCents: 500000, quantity: 1, amountCents: 500000, isDone: true, createdBy: DR_REYES_MEMBERSHIP_ID, updatedBy: DR_REYES_MEMBERSHIP_ID },
  ]).onConflictDoNothing();

  // ── 3. Payments ───────────────────────────────────────────────────
  await db.insert(dentalPayments).values([
    // Pay1: INV-0001 full, cash
    {
      id: PAYMENT_01,
      invoiceId: INVOICE_01,
      patientId: PATIENT_JUAN_ID,
      branchId: BRANCH_ID,
      amountCents: 150000,
      method: 'cash',
      receiptNumber: 'RCP-2026-0001',
      recordedByMemberId: ANA_SANTOS_MEMBERSHIP_ID,
      createdBy: ANA_SANTOS_MEMBERSHIP_ID,
      updatedBy: ANA_SANTOS_MEMBERSHIP_ID,
    },
    // Pay2: INV-0002 full, cash
    {
      id: PAYMENT_02,
      invoiceId: INVOICE_02,
      patientId: PATIENT_JUAN_ID,
      branchId: BRANCH_ID,
      amountCents: 250000,
      method: 'cash',
      receiptNumber: 'RCP-2026-0002',
      recordedByMemberId: ANA_SANTOS_MEMBERSHIP_ID,
      createdBy: ANA_SANTOS_MEMBERSHIP_ID,
      updatedBy: ANA_SANTOS_MEMBERSHIP_ID,
    },
    // Pay3: INV-0003 full, cash
    {
      id: PAYMENT_03,
      invoiceId: INVOICE_03,
      patientId: PATIENT_ROSA_ID,
      branchId: BRANCH_ID,
      amountCents: 80000,
      method: 'cash',
      receiptNumber: 'RCP-2026-0003',
      recordedByMemberId: ANA_SANTOS_MEMBERSHIP_ID,
      createdBy: ANA_SANTOS_MEMBERSHIP_ID,
      updatedBy: ANA_SANTOS_MEMBERSHIP_ID,
    },
    // Pay4: INV-0004 partial 500000 centavos, cash
    {
      id: PAYMENT_04,
      invoiceId: INVOICE_04,
      patientId: PATIENT_ROSA_ID,
      branchId: BRANCH_ID,
      amountCents: 500000,
      method: 'cash',
      receiptNumber: 'RCP-2026-0004',
      notes: 'Partial payment — remaining PHP10,000 to be collected on follow-up',
      recordedByMemberId: ANA_SANTOS_MEMBERSHIP_ID,
      createdBy: ANA_SANTOS_MEMBERSHIP_ID,
      updatedBy: ANA_SANTOS_MEMBERSHIP_ID,
    },
    // Pay5: INV-0005 full, cash
    {
      id: PAYMENT_05,
      invoiceId: INVOICE_05,
      patientId: PATIENT_CARLOS_ID,
      branchId: BRANCH_ID,
      amountCents: 150000,
      method: 'cash',
      receiptNumber: 'RCP-2026-0005',
      recordedByMemberId: ANA_SANTOS_MEMBERSHIP_ID,
      createdBy: ANA_SANTOS_MEMBERSHIP_ID,
      updatedBy: ANA_SANTOS_MEMBERSHIP_ID,
    },
    // Pay6: INV-0007 full, cash (Liza)
    {
      id: PAYMENT_06,
      invoiceId: INVOICE_07,
      patientId: PATIENT_LIZA_ID,
      branchId: BRANCH_ID,
      amountCents: 150000,
      method: 'cash',
      receiptNumber: 'RCP-2026-0006',
      recordedByMemberId: ANA_SANTOS_MEMBERSHIP_ID,
      createdBy: ANA_SANTOS_MEMBERSHIP_ID,
      updatedBy: ANA_SANTOS_MEMBERSHIP_ID,
    },
    // Pay7: INV-0008 full, card (Ben extraction)
    {
      id: PAYMENT_07,
      invoiceId: INVOICE_08,
      patientId: PATIENT_BEN_ID,
      branchId: BRANCH_ID,
      amountCents: 500000,
      method: 'card',
      receiptNumber: 'RCP-2026-0007',
      recordedByMemberId: ANA_SANTOS_MEMBERSHIP_ID,
      createdBy: ANA_SANTOS_MEMBERSHIP_ID,
      updatedBy: ANA_SANTOS_MEMBERSHIP_ID,
    },
  ]).onConflictDoNothing();

  // ── 4. Payment Plan for Carlos INV-0006 (PHP20k crown) ───────────
  await db.insert(dentalPaymentPlans).values({
    id: PLAN_01,
    invoiceId: INVOICE_06,
    patientId: PATIENT_CARLOS_ID,
    totalCents: 2000000,
    numberOfInstallments: 4,
    frequency: 'monthly',
    startDate: new Date('2026-05-01T00:00:00+08:00'),
    amountPerInstallmentCents: 500000,
    status: 'on_track',
    createdBy: DR_REYES_MEMBERSHIP_ID,
    updatedBy: DR_REYES_MEMBERSHIP_ID,
  }).onConflictDoNothing();

  // 4 installments: May, Jun, Jul, Aug — all pending
  await db.insert(dentalPaymentPlanInstallments).values([
    {
      id: INSTALLMENT_01,
      planId: PLAN_01,
      installmentNumber: 1,
      dueDate: new Date('2026-05-01T00:00:00+08:00'),
      amountCents: 500000,
      paidCents: 0,
      status: 'pending',
      createdBy: DR_REYES_MEMBERSHIP_ID,
      updatedBy: DR_REYES_MEMBERSHIP_ID,
    },
    {
      id: INSTALLMENT_02,
      planId: PLAN_01,
      installmentNumber: 2,
      dueDate: new Date('2026-06-01T00:00:00+08:00'),
      amountCents: 500000,
      paidCents: 0,
      status: 'pending',
      createdBy: DR_REYES_MEMBERSHIP_ID,
      updatedBy: DR_REYES_MEMBERSHIP_ID,
    },
    {
      id: INSTALLMENT_03,
      planId: PLAN_01,
      installmentNumber: 3,
      dueDate: new Date('2026-07-01T00:00:00+08:00'),
      amountCents: 500000,
      paidCents: 0,
      status: 'pending',
      createdBy: DR_REYES_MEMBERSHIP_ID,
      updatedBy: DR_REYES_MEMBERSHIP_ID,
    },
    {
      id: INSTALLMENT_04,
      planId: PLAN_01,
      installmentNumber: 4,
      dueDate: new Date('2026-08-01T00:00:00+08:00'),
      amountCents: 500000,
      paidCents: 0,
      status: 'pending',
      createdBy: DR_REYES_MEMBERSHIP_ID,
      updatedBy: DR_REYES_MEMBERSHIP_ID,
    },
  ]).onConflictDoNothing();

  console.log('   ✅ 8 invoices, 8 line items, 7 payments, 1 payment plan (4 installments)');
}
