/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DentalOnboardingRouteImport } from './routes/dental-onboarding'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImagingCephReportImageIdRouteImport } from './routes/imaging-ceph-report.$imageId'
import { Route as BookBranchIdRouteImport } from './routes/book.$branchId'
import { Route as AuthPinSelectRouteImport } from './routes/auth/pin-select'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as WorkspaceQueueBoardRouteImport } from './routes/_workspace/queue-board'
import { Route as WorkspacePatientIdRouteImport } from './routes/_workspace/$patientId'
import { Route as DashboardStaffRouteImport } from './routes/_dashboard/staff'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardReportsRouteImport } from './routes/_dashboard/reports'
import { Route as DashboardPatientsRouteImport } from './routes/_dashboard/patients'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardCalendarRouteImport } from './routes/_dashboard/calendar'
import { Route as DashboardBillingRouteImport } from './routes/_dashboard/billing'
import { Route as PortalPortalIndexRouteImport } from './routes/_portal/portal.index'
import { Route as AuthPinEntryMemberIdRouteImport } from './routes/auth/pin-entry.$memberId'
import { Route as PortalPortalBillsRouteImport } from './routes/_portal/portal.bills'
import { Route as PortalPortalAppointmentsRouteImport } from './routes/_portal/portal.appointments'
import { Route as DashboardPatientsPatientIdRouteImport } from './routes/_dashboard/patients_/$patientId'
import { Route as WorkspacePatientIdCasePresentationPresentationIdRouteImport } from './routes/_workspace/$patientId.case-presentation.$presentationId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalOnboardingRoute = DentalOnboardingRouteImport.update({
  id: '/dental-onboarding',
  path: '/dental-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagingCephReportImageIdRoute =
  ImagingCephReportImageIdRouteImport.update({
    id: '/imaging-ceph-report/$imageId',
    path: '/imaging-ceph-report/$imageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookBranchIdRoute = BookBranchIdRouteImport.update({
  id: '/book/$branchId',
  path: '/book/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPinSelectRoute = AuthPinSelectRouteImport.update({
  id: '/auth/pin-select',
  path: '/auth/pin-select',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceQueueBoardRoute = WorkspaceQueueBoardRouteImport.update({
  id: '/queue-board',
  path: '/queue-board',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePatientIdRoute = WorkspacePatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => WorkspaceRoute,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientsRoute = DashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalPortalIndexRoute = PortalPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => PortalRoute,
} as any)
const AuthPinEntryMemberIdRoute = AuthPinEntryMemberIdRouteImport.update({
  id: '/auth/pin-entry/$memberId',
  path: '/auth/pin-entry/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPortalBillsRoute = PortalPortalBillsRouteImport.update({
  id: '/portal/bills',
  path: '/portal/bills',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPortalAppointmentsRoute =
  PortalPortalAppointmentsRouteImport.update({
    id: '/portal/appointments',
    path: '/portal/appointments',
    getParentRoute: () => PortalRoute,
  } as any)
const DashboardPatientsPatientIdRoute =
  DashboardPatientsPatientIdRouteImport.update({
    id: '/patients_/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => DashboardRoute,
  } as any)
const WorkspacePatientIdCasePresentationPresentationIdRoute =
  WorkspacePatientIdCasePresentationPresentationIdRouteImport.update({
    id: '/case-presentation/$presentationId',
    path: '/case-presentation/$presentationId',
    getParentRoute: () => WorkspacePatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dental-onboarding': typeof DentalOnboardingRoute
  '/onboarding': typeof OnboardingRoute
  '/verify-email': typeof VerifyEmailRoute
  '/billing': typeof DashboardBillingRoute
  '/calendar': typeof DashboardCalendarRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/patients': typeof DashboardPatientsRoute
  '/reports': typeof DashboardReportsRoute
  '/settings': typeof DashboardSettingsRoute
  '/staff': typeof DashboardStaffRoute
  '/$patientId': typeof WorkspacePatientIdRouteWithChildren
  '/queue-board': typeof WorkspaceQueueBoardRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/auth/pin-select': typeof AuthPinSelectRoute
  '/book/$branchId': typeof BookBranchIdRoute
  '/imaging-ceph-report/$imageId': typeof ImagingCephReportImageIdRoute
  '/patients/$patientId': typeof DashboardPatientsPatientIdRoute
  '/portal/appointments': typeof PortalPortalAppointmentsRoute
  '/portal/bills': typeof PortalPortalBillsRoute
  '/auth/pin-entry/$memberId': typeof AuthPinEntryMemberIdRoute
  '/portal/': typeof PortalPortalIndexRoute
  '/$patientId/case-presentation/$presentationId': typeof WorkspacePatientIdCasePresentationPresentationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dental-onboarding': typeof DentalOnboardingRoute
  '/onboarding': typeof OnboardingRoute
  '/verify-email': typeof VerifyEmailRoute
  '/billing': typeof DashboardBillingRoute
  '/calendar': typeof DashboardCalendarRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/patients': typeof DashboardPatientsRoute
  '/reports': typeof DashboardReportsRoute
  '/settings': typeof DashboardSettingsRoute
  '/staff': typeof DashboardStaffRoute
  '/$patientId': typeof WorkspacePatientIdRouteWithChildren
  '/queue-board': typeof WorkspaceQueueBoardRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/auth/pin-select': typeof AuthPinSelectRoute
  '/book/$branchId': typeof BookBranchIdRoute
  '/imaging-ceph-report/$imageId': typeof ImagingCephReportImageIdRoute
  '/patients/$patientId': typeof DashboardPatientsPatientIdRoute
  '/portal/appointments': typeof PortalPortalAppointmentsRoute
  '/portal/bills': typeof PortalPortalBillsRoute
  '/auth/pin-entry/$memberId': typeof AuthPinEntryMemberIdRoute
  '/portal': typeof PortalPortalIndexRoute
  '/$patientId/case-presentation/$presentationId': typeof WorkspacePatientIdCasePresentationPresentationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_portal': typeof PortalRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/dental-onboarding': typeof DentalOnboardingRoute
  '/onboarding': typeof OnboardingRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_dashboard/billing': typeof DashboardBillingRoute
  '/_dashboard/calendar': typeof DashboardCalendarRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/patients': typeof DashboardPatientsRoute
  '/_dashboard/reports': typeof DashboardReportsRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/staff': typeof DashboardStaffRoute
  '/_workspace/$patientId': typeof WorkspacePatientIdRouteWithChildren
  '/_workspace/queue-board': typeof WorkspaceQueueBoardRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/auth/pin-select': typeof AuthPinSelectRoute
  '/book/$branchId': typeof BookBranchIdRoute
  '/imaging-ceph-report/$imageId': typeof ImagingCephReportImageIdRoute
  '/_dashboard/patients_/$patientId': typeof DashboardPatientsPatientIdRoute
  '/_portal/portal/appointments': typeof PortalPortalAppointmentsRoute
  '/_portal/portal/bills': typeof PortalPortalBillsRoute
  '/auth/pin-entry/$memberId': typeof AuthPinEntryMemberIdRoute
  '/_portal/portal/': typeof PortalPortalIndexRoute
  '/_workspace/$patientId/case-presentation/$presentationId': typeof WorkspacePatientIdCasePresentationPresentationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dental-onboarding'
    | '/onboarding'
    | '/verify-email'
    | '/billing'
    | '/calendar'
    | '/dashboard'
    | '/patients'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/$patientId'
    | '/queue-board'
    | '/auth/$authView'
    | '/auth/pin-select'
    | '/book/$branchId'
    | '/imaging-ceph-report/$imageId'
    | '/patients/$patientId'
    | '/portal/appointments'
    | '/portal/bills'
    | '/auth/pin-entry/$memberId'
    | '/portal/'
    | '/$patientId/case-presentation/$presentationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dental-onboarding'
    | '/onboarding'
    | '/verify-email'
    | '/billing'
    | '/calendar'
    | '/dashboard'
    | '/patients'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/$patientId'
    | '/queue-board'
    | '/auth/$authView'
    | '/auth/pin-select'
    | '/book/$branchId'
    | '/imaging-ceph-report/$imageId'
    | '/patients/$patientId'
    | '/portal/appointments'
    | '/portal/bills'
    | '/auth/pin-entry/$memberId'
    | '/portal'
    | '/$patientId/case-presentation/$presentationId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_portal'
    | '/_workspace'
    | '/dental-onboarding'
    | '/onboarding'
    | '/verify-email'
    | '/_dashboard/billing'
    | '/_dashboard/calendar'
    | '/_dashboard/dashboard'
    | '/_dashboard/patients'
    | '/_dashboard/reports'
    | '/_dashboard/settings'
    | '/_dashboard/staff'
    | '/_workspace/$patientId'
    | '/_workspace/queue-board'
    | '/auth/$authView'
    | '/auth/pin-select'
    | '/book/$branchId'
    | '/imaging-ceph-report/$imageId'
    | '/_dashboard/patients_/$patientId'
    | '/_portal/portal/appointments'
    | '/_portal/portal/bills'
    | '/auth/pin-entry/$memberId'
    | '/_portal/portal/'
    | '/_workspace/$patientId/case-presentation/$presentationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  DentalOnboardingRoute: typeof DentalOnboardingRoute
  OnboardingRoute: typeof OnboardingRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  AuthPinSelectRoute: typeof AuthPinSelectRoute
  BookBranchIdRoute: typeof BookBranchIdRoute
  ImagingCephReportImageIdRoute: typeof ImagingCephReportImageIdRoute
  AuthPinEntryMemberIdRoute: typeof AuthPinEntryMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-onboarding': {
      id: '/dental-onboarding'
      path: '/dental-onboarding'
      fullPath: '/dental-onboarding'
      preLoaderRoute: typeof DentalOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imaging-ceph-report/$imageId': {
      id: '/imaging-ceph-report/$imageId'
      path: '/imaging-ceph-report/$imageId'
      fullPath: '/imaging-ceph-report/$imageId'
      preLoaderRoute: typeof ImagingCephReportImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$branchId': {
      id: '/book/$branchId'
      path: '/book/$branchId'
      fullPath: '/book/$branchId'
      preLoaderRoute: typeof BookBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pin-select': {
      id: '/auth/pin-select'
      path: '/auth/pin-select'
      fullPath: '/auth/pin-select'
      preLoaderRoute: typeof AuthPinSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/queue-board': {
      id: '/_workspace/queue-board'
      path: '/queue-board'
      fullPath: '/queue-board'
      preLoaderRoute: typeof WorkspaceQueueBoardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/$patientId': {
      id: '/_workspace/$patientId'
      path: '/$patientId'
      fullPath: '/$patientId'
      preLoaderRoute: typeof WorkspacePatientIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_dashboard/staff': {
      id: '/_dashboard/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports': {
      id: '/_dashboard/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/patients': {
      id: '/_dashboard/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof DashboardPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/calendar': {
      id: '/_dashboard/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/billing': {
      id: '/_dashboard/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_portal/portal/': {
      id: '/_portal/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalPortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/auth/pin-entry/$memberId': {
      id: '/auth/pin-entry/$memberId'
      path: '/auth/pin-entry/$memberId'
      fullPath: '/auth/pin-entry/$memberId'
      preLoaderRoute: typeof AuthPinEntryMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/portal/bills': {
      id: '/_portal/portal/bills'
      path: '/portal/bills'
      fullPath: '/portal/bills'
      preLoaderRoute: typeof PortalPortalBillsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/appointments': {
      id: '/_portal/portal/appointments'
      path: '/portal/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof PortalPortalAppointmentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_dashboard/patients_/$patientId': {
      id: '/_dashboard/patients_/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof DashboardPatientsPatientIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_workspace/$patientId/case-presentation/$presentationId': {
      id: '/_workspace/$patientId/case-presentation/$presentationId'
      path: '/case-presentation/$presentationId'
      fullPath: '/$patientId/case-presentation/$presentationId'
      preLoaderRoute: typeof WorkspacePatientIdCasePresentationPresentationIdRouteImport
      parentRoute: typeof WorkspacePatientIdRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardPatientsRoute: typeof DashboardPatientsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStaffRoute: typeof DashboardStaffRoute
  DashboardPatientsPatientIdRoute: typeof DashboardPatientsPatientIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardPatientsRoute: DashboardPatientsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStaffRoute: DashboardStaffRoute,
  DashboardPatientsPatientIdRoute: DashboardPatientsPatientIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PortalRouteChildren {
  PortalPortalAppointmentsRoute: typeof PortalPortalAppointmentsRoute
  PortalPortalBillsRoute: typeof PortalPortalBillsRoute
  PortalPortalIndexRoute: typeof PortalPortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalPortalAppointmentsRoute: PortalPortalAppointmentsRoute,
  PortalPortalBillsRoute: PortalPortalBillsRoute,
  PortalPortalIndexRoute: PortalPortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface WorkspacePatientIdRouteChildren {
  WorkspacePatientIdCasePresentationPresentationIdRoute: typeof WorkspacePatientIdCasePresentationPresentationIdRoute
}

const WorkspacePatientIdRouteChildren: WorkspacePatientIdRouteChildren = {
  WorkspacePatientIdCasePresentationPresentationIdRoute:
    WorkspacePatientIdCasePresentationPresentationIdRoute,
}

const WorkspacePatientIdRouteWithChildren =
  WorkspacePatientIdRoute._addFileChildren(WorkspacePatientIdRouteChildren)

interface WorkspaceRouteChildren {
  WorkspacePatientIdRoute: typeof WorkspacePatientIdRouteWithChildren
  WorkspaceQueueBoardRoute: typeof WorkspaceQueueBoardRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspacePatientIdRoute: WorkspacePatientIdRouteWithChildren,
  WorkspaceQueueBoardRoute: WorkspaceQueueBoardRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  DentalOnboardingRoute: DentalOnboardingRoute,
  OnboardingRoute: OnboardingRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  AuthPinSelectRoute: AuthPinSelectRoute,
  BookBranchIdRoute: BookBranchIdRoute,
  ImagingCephReportImageIdRoute: ImagingCephReportImageIdRoute,
  AuthPinEntryMemberIdRoute: AuthPinEntryMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
